config/routes.rb
Expirer::Application.routes.draw do
  resources :point_line_items do
    collection do
      get :delete_expired
      get :emulate_expiration
    end
  end

  resources :users

  root 'users#index'

  

end

app/models/point_expirer.rb
class PointExpirer
  def self.expire(date) 
    if lis = PointLineItem.where("DATE(created_at) = ? AND points > 0", date.ago(1.year + 1.day).to_date) and lis.any?
      lis.each do |li|
        redeems = PointLineItem.where('created_at > ? AND points < 0 AND source = ?', li.created_at, 'Redeemed with an order')
        if redeems.any?
          if (li.points + redeems.map(&:points).sum > 0)
            PointLineItem.create(points: -redeems.first.points_actual, source: "Points ##{li.id} expired", user: li.user)
          end
        else
          PointLineItem.create(points: -li.points, source: "Points ##{li.id} expired", user: li.user)
        end
      end
    end
  end
end

app/models/point_line_item.rb
class PointLineItem < ActiveRecord::Base
  belongs_to :user
  scope :by_period, ->(from, to) {where('created_at BETWEEN ? AND ?', from, to)}
end

app/models/user.rb
class User < ActiveRecord::Base
  has_many :point_line_items

  validates :name, uniqueness: true
end

app/controllers/application_controller.rb
class ApplicationController < ActionController::Base
  # Prevent CSRF attacks by raising an exception.
  # For APIs, you may want to use :null_session instead.
  protect_from_forgery with: :exception
end

app/controllers/point_line_items_controller.rb
class PointLineItemsController < ApplicationController
  before_action :set_point_line_item, only: [:show, :edit, :update, :destroy]

  # GET /point_line_items
  # GET /point_line_items.json
  def index
    @point_line_items = PointLineItem.all
  end

  # GET /point_line_items/1
  # GET /point_line_items/1.json
  def show
  end

  # GET /point_line_items/new
  def new
    @point_line_item = PointLineItem.new
  end

  # GET /point_line_items/1/edit
  def edit
  end

  # POST /point_line_items
  # POST /point_line_items.json
  def create
    @point_line_item = PointLineItem.new(point_line_item_params)

    respond_to do |format|
      if @point_line_item.save
        format.html { redirect_to @point_line_item, notice: 'Point line item was successfully created.' }
        format.json { render action: 'show', status: :created, location: @point_line_item }
      else
        format.html { render action: 'new' }
        format.json { render json: @point_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /point_line_items/1
  # PATCH/PUT /point_line_items/1.json
  def update
    respond_to do |format|
      if @point_line_item.update(point_line_item_params)
        format.html { redirect_to @point_line_item, notice: 'Point line item was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @point_line_item.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /point_line_items/1
  # DELETE /point_line_items/1.json
  def destroy
    @point_line_item.destroy
    respond_to do |format|
      format.html { redirect_to point_line_items_url }
      format.json { head :no_content }
    end
  end

  def delete_expired
    PointLineItem.where('source LIKE ?', '%expired%').delete_all
    redirect_to action: :index
  end

  def emulate_expiration
    PointLineItem.all.map(&:created_at).each {|d| PointExpirer.expire(d.since(1.year + 1.day))}
    redirect_to action: :index
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_point_line_item
      @point_line_item = PointLineItem.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def point_line_item_params
      params.require(:point_line_item).permit(:user_id, :points, :source, :points_actual)
    end
end

app/controllers/users_controller.rb
class UsersController < ApplicationController
  before_action :set_user, only: [:show, :edit, :update, :destroy]

  # GET /users
  # GET /users.json
  def index
    @users = User.all
  end

  # GET /users/1
  # GET /users/1.json
  def show
  end

  # GET /users/new
  def new
    @user = User.new
  end

  # GET /users/1/edit
  def edit
  end

  # POST /users
  # POST /users.json
  def create
    @user = User.new(user_params)

    respond_to do |format|
      if @user.save
        format.html { redirect_to @user, notice: 'User was successfully created.' }
        format.json { render action: 'show', status: :created, location: @user }
      else
        format.html { render action: 'new' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # PATCH/PUT /users/1
  # PATCH/PUT /users/1.json
  def update
    respond_to do |format|
      if @user.update(user_params)
        format.html { redirect_to @user, notice: 'User was successfully updated.' }
        format.json { head :no_content }
      else
        format.html { render action: 'edit' }
        format.json { render json: @user.errors, status: :unprocessable_entity }
      end
    end
  end

  # DELETE /users/1
  # DELETE /users/1.json
  def destroy
    @user.destroy
    respond_to do |format|
      format.html { redirect_to users_url }
      format.json { head :no_content }
    end
  end

  private
    # Use callbacks to share common setup or constraints between actions.
    def set_user
      @user = User.find(params[:id])
    end

    # Never trust parameters from the scary internet, only allow the white list through.
    def user_params
      params.require(:user).permit(:name)
    end
end

app/helpers/application_helper.rb
module ApplicationHelper
end

app/helpers/point_line_items_helper.rb
module PointLineItemsHelper
end

app/helpers/users_helper.rb
module UsersHelper
end

app/views/layouts/application.html.erb
<!DOCTYPE html>
<html>
<head>
  <title>Expirer</title>
  <%= stylesheet_link_tag    "application", media: "all", "data-turbolinks-track" => true %>
  <%= javascript_include_tag "application", "data-turbolinks-track" => true %>
  <%= csrf_meta_tags %>
</head>
<body>

<%= yield %>

</body>
</html>

app/views/point_line_items/_form.html.erb
<%= form_for(@point_line_item) do |f| %>
  <% if @point_line_item.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@point_line_item.errors.count, "error") %> prohibited this point_line_item from being saved:</h2>

      <ul>
      <% @point_line_item.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :user_id %><br>
    <%= f.number_field :user_id %>
  </div>
  <div class="field">
    <%= f.label :points %><br>
    <%= f.text_field :points %>
  </div>
  <div class="field">
    <%= f.label :source %><br>
    <%= f.text_field :source %>
  </div>
  <div class="field">
    <%= f.label :points_actual %><br>
    <%= f.text_field :points_actual %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/point_line_items/edit.html.erb
<h1>Editing point_line_item</h1>

<%= render 'form' %>

<%= link_to 'Show', @point_line_item %> |
<%= link_to 'Back', point_line_items_path %>

app/views/point_line_items/index.html.erb
<h1>Listing point_line_items</h1>

<table>
  <thead>
    <tr>
      <th>Id</th>
      <th>User</th>
      <th>Points</th>
      <th>Source</th>
      <th>Created At</th>
      <th>Points Actual</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @point_line_items.each do |point_line_item| %>
      <tr>
        <td><%= point_line_item.id %></td>
        <td><%= point_line_item.user_id %></td>
        <td><%= point_line_item.points %></td>
        <td><%= point_line_item.source %></td>
        <td><%= l point_line_item.created_at, format: :short %></td>
        <td><%= point_line_item.points_actual %></td>
        <td><%= link_to 'Show', point_line_item %></td>
        <td><%= link_to 'Edit', edit_point_line_item_path(point_line_item) %></td>
        <td><%= link_to 'Destroy', point_line_item, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New Point line item', new_point_line_item_path %>
<br>
<%= link_to 'Delete expired points', delete_expired_point_line_items_path %>
<br>
<%= link_to 'Emulate points expiration', emulate_expiration_point_line_items_path %>

app/views/point_line_items/new.html.erb
<h1>New point_line_item</h1>

<%= render 'form' %>

<%= link_to 'Back', point_line_items_path %>

app/views/point_line_items/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>User:</strong>
  <%= @point_line_item.user_id %>
</p>

<p>
  <strong>Points:</strong>
  <%= @point_line_item.points %>
</p>

<p>
  <strong>Source:</strong>
  <%= @point_line_item.source %>
</p>

<%= link_to 'Edit', edit_point_line_item_path(@point_line_item) %> |
<%= link_to 'Back', point_line_items_path %>

app/views/users/_form.html.erb
<%= form_for(@user) do |f| %>
  <% if @user.errors.any? %>
    <div id="error_explanation">
      <h2><%= pluralize(@user.errors.count, "error") %> prohibited this user from being saved:</h2>

      <ul>
      <% @user.errors.full_messages.each do |msg| %>
        <li><%= msg %></li>
      <% end %>
      </ul>
    </div>
  <% end %>

  <div class="field">
    <%= f.label :name %><br>
    <%= f.text_field :name %>
  </div>
  <div class="actions">
    <%= f.submit %>
  </div>
<% end %>

app/views/users/edit.html.erb
<h1>Editing user</h1>

<%= render 'form' %>

<%= link_to 'Show', @user %> |
<%= link_to 'Back', users_path %>

app/views/users/index.html.erb
<h1>Listing users</h1>

<table>
  <thead>
    <tr>
      <th>Name</th>
      <th></th>
      <th></th>
      <th></th>
    </tr>
  </thead>

  <tbody>
    <% @users.each do |user| %>
      <tr>
        <td><%= user.name %></td>
        <td><%= link_to 'Show', user %></td>
        <td><%= link_to 'Edit', edit_user_path(user) %></td>
        <td><%= link_to 'Destroy', user, method: :delete, data: { confirm: 'Are you sure?' } %></td>
      </tr>
    <% end %>
  </tbody>
</table>

<br>

<%= link_to 'New User', new_user_path %>

app/views/users/new.html.erb
<h1>New user</h1>

<%= render 'form' %>

<%= link_to 'Back', users_path %>

app/views/users/show.html.erb
<p id="notice"><%= notice %></p>

<p>
  <strong>Name:</strong>
  <%= @user.name %>
</p>

<%= link_to 'Edit', edit_user_path(@user) %> |
<%= link_to 'Back', users_path %>